### PR TITLE
Adding a student course section data field to the Student class.

### PR DESCRIPTION
**Pull request by davis68**
This adds a `section` field to the Student class.  Right now this doesn't impact anything else, but it's a minor piece towards the `ReportApp` I'm working on (#436).

### CODE REVIEW

**Comment by jhamrick** [comment]
This seems reasonable, though it will cause issues with existing databases (since they won't have that column). @ellisonbg are you fine with this change?

Also, @davis68 , would you mind just adding a few test cases for this? Probably if you add some in the following locations, that would be sufficient:

* https://github.com/jupyter/nbgrader/blob/master/nbgrader/tests/api/test_models.py#L172
* https://github.com/jupyter/nbgrader/blob/master/nbgrader/tests/api/test_gradebook.py#L38

**Comment by ellisonbg** [comment]
this would be fine - I am deploying off a branch for the rest of this
quarter so it won't mess up my current deployment.

On Sun, Feb 21, 2016 at 11:51 AM, Jessica B. Hamrick <
notifications@github.com> wrote:

> This seems reasonable, though it will cause issues with existing databases
> (since they won't have that column). @ellisonbg
> <https://github.com/ellisonbg> are you fine with this change?
>
> Also, @davis68 <https://github.com/davis68> , would you mind just adding
> a few test cases for this? Probably if you add some in the following
> locations, that would be sufficient:
>
>    -
>    https://github.com/jupyter/nbgrader/blob/master/nbgrader/tests/api/test_models.py#L172
>    -
>    https://github.com/jupyter/nbgrader/blob/master/nbgrader/tests/api/test_gradebook.py#L38
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/nbgrader/pull/441#issuecomment-186897340>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by jhamrick** [comment]
Also, I think you will need to rebase this against master.

**Comment by davis68** [comment]
We've had our system in production for a few months now, and I've been fairly actively tinkering with the system.  I have concluded that adding a by-section option seems to be an architectural dead end (right now), and that it's better (read:  much easier) to set up parallel installations for parallel sections of the course.

On that basis, I'm going to withdraw this PR for the time being.

**Pull request closed without merging**
