### PR TITLE
Update Release Scripts

### PR DESCRIPTION
**Pull request by blink1073**
See https://github.com/jupyter-server/jupyter_releaser/pull/557 for context.

### CODE REVIEW

**Comment by blink1073** [comment]
@brichet can you please add `blink1073` to the PyPI project so I can set up trusted publishing?

**Comment by blink1073** [comment]
Also, you'll need to create an npm token and replace the NPM_TOKEN secret.

**Comment by brichet** [comment]
Thanks @blink1073 for quick update.

Look like I can't add you on PyPI


Maybe @jtpio  or @SylvainCorlay can ? And if you can please also add me as owner, it would be great.

**Comment by brichet** [comment]
> Also, you'll need to create an npm token and replace the NPM_TOKEN secret.

Not sure to understand that one, the current NPM_TOKEN secret is still valid.
Do U have to change something when created it again ?

**Comment by blink1073** [comment]
> Not sure to understand that one, the current NPM_TOKEN secret is still valid.

There wasn't one set, I just set it to the one for the `@jupyter` org, but this package isn't in that namespace.  I don't have access to the npm package.

**Comment by brichet** [comment]
> > Not sure to understand that one, the current NPM_TOKEN secret is still valid.
> 
> There wasn't one set, I just set it to the one for the `@jupyter` org, but this package isn't in that namespace. I don't have access to the npm package.

Strange, I used the releaser to push on NPM 2 days ago, using a token that I created
Screenshot from 2024-03-28 15-55-44

No matter, I updated the value of the NPM_TOKEN.

Perhaps we should move the package to the `@jupyter` namespace later. We could then use the token from the `@jupyter` org, no ?

**Comment by blink1073** [comment]
> Perhaps we should move the package to the @jupyter namespace later. We could then use the token from the @jupyter org, no ?

Yes, all you'd have to do is rename it in `package.json` and ping me to update the token.

**Comment by blink1073** [comment]
Trusted publishing is set up, ready to go!

**Comment by brichet** [comment]
Thanks a lot @blink1073

**Comment by blink1073** [comment]
No problem!

**Comment by brichet** [comment]
> > Perhaps we should move the package to the @jupyter namespace later. We could then use the token from the @jupyter org, no ?
> 
> Yes, all you'd have to do is rename it in `package.json` and ping me to update the token.

Do you know if it will be possible to bring the history back to the new package ?

**Comment by blink1073** [comment]
> Do you know if it will be possible to bring the history back to the new package ?

I don't know, I haven't dealt with npm packages directly in a few years.

**Pull request merged**
