### PR TITLE
Unpinning ipython version to allow to work with 3.0 and 3.1, etc.

### PR DESCRIPTION
**Pull request by ellisonbg**
Solves #183

### CODE REVIEW

**Comment by ellisonbg** [comment]
This is a trivial change, tests are passing so I am going to merge. @jhamrick let me know if you see any problems with this.

**Comment by jhamrick** [comment]
I don't think the current version of nbgrader will work on either 3.0 or 3.1 because it depends on https://github.com/ipython/ipython/pull/8073 , which is in 4.0 only. The tests are passing because I clamped the version of IPython in the tests to a specific commit before the Big Split started happening:

https://github.com/jupyter/nbgrader/blob/master/.travis.yml#L21

Perhaps we could have the requirements list an egg from github with the specific commit?

**Comment by jhamrick** [comment]
As an interim/alternate solution, if you wanted to be able to rely on 3.1 (which probably would be better), we could implement the functionality of ipython/ipython#8073 in nbgrader just until IPython stabilizes.

**Comment by ellisonbg** [comment]
Hmmm, I am pinning my class to 3.x. Do you think Bach porting that to 3.x is difficult?

**Comment by jhamrick** [comment]
I don't think it is difficult, but it's not really a bugfix so I don't know if it is appropriate for 3.1. But maybe that's ok, if it really is needed by nbgrader?

**Comment by Carreau** [comment]
I think it's ok to backport if really needed by nbgrader. It does not change API just add things.

**Comment by ellisonbg** [comment]
OK I think I am +1 on the backport.

On Wed, Apr 1, 2015 at 9:41 AM, Matthias Bussonnier <
notifications@github.com> wrote:

> I think it's ok to backport if really needed by nbgrader. It does not
> change API just add things.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/nbgrader/pull/184#issuecomment-88537786>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by Carreau** [comment]
Backport PR made : https://github.com/ipython/ipython/pull/8220

**Comment by ellisonbg** [comment]
Thanks!!!

On Wed, Apr 1, 2015 at 11:08 AM, Matthias Bussonnier <
notifications@github.com> wrote:

> Backport PR made : ipython/ipython#8220
> <https://github.com/ipython/ipython/pull/8220>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/nbgrader/pull/184#issuecomment-88579779>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Pull request merged**
