### PR TITLE
Add coverage to tests

### LINKED ISSUE #140: Coverage
Would be nice to enable coverage. 

Coveralls.io should have [access](https://coveralls.io/r/jupyter/nbgrader) now. 

Not a reason to Slack Off from Your Ph.D :-P

### PR DESCRIPTION
**Pull request by jhamrick**
Fixes #140

### CODE REVIEW

**Comment by jhamrick** [comment]
Coverage is 78%, not too shabby! :smile:

**Comment by Carreau** [comment]
And that's what you call quiet evening...

**Comment by jhamrick** [comment]
Well, as soon as this last build passes I am going to merge it and then will go make dinner and then not do any more coding for the rest of the evening.

**Comment by Carreau** [comment]
> Well, as soon as this last build passes I am going to merge it and then will go make dinner and then not do any more coding for the rest of the evening.

I'll take care of merging. Go eat.

**Comment by jhamrick** [comment]
Ok, thanks!

**Comment by Carreau** [comment]
That give me the impression of being useful.

**Pull request merged**
