### PR TITLE
add SAS codestub and autograde for metakernel based non-python kernels

### PR DESCRIPTION
**Pull request by jld23**
similar to #870 I've added a code stub to get people started using nbgrader for teaching [SAS](https://github.com/sassoftware/sas_kernel).
This is a one line change.

The more consequential change is supporting auto-grading when cells return as a stream and then `output.name` is `stderr`.
This issue was discussed in #1173 specifically for octave and @jhamrick indicated support for a change to compare `output.output_type == "stream" and output.name == "stderr":`

This change is  useful because it allows the many [non-Python language kernels based on metakernel](https://github.com/Calysto/metakernel#kernels-based-on-metakernel), not just octave, to integrate with nbgrader if they use the metakernel `Error` or `Error_display` methods.

### CODE REVIEW

**Comment by jld23** [comment]
I've never used `codecov` before it appears the check is failing on my typo commit. I'm not sure how to remediate.

**Comment by jld23** [comment]
Is there anything needed from me to advance this PR?

**Comment by BertR** [comment]
Hi @jld23, this looks good to me

**Comment by jld23** [comment]
@BertR, I got a windows system working and I can confirm I'm seeing issues with 0.70.dev and not with pip installed 0.6.1 I'm getting errors where I don't think my code is involved like updating the notebooks `nbgrader update source`.

Not sure how you want to proceed.

**Comment by BertR** [comment]
> @BertR, I got a windows system working and I can confirm I'm seeing issues with 0.7.0.dev0 (my PR branch) and not with pip installed 0.6.1 I'm getting errors where I don't think my code is involved like updating the notebooks `nbgrader update source`.
> 
> Not sure how you want to proceed.

@jld23 it's possible this failed due to broken pypi dependencies in the master branch which have now been fixed.
Could you rebase and push again?

**Pull request merged**
