### PR TITLE
Assignment names breaking regex

### LINKED ISSUE #1738: Assignments_ids with `()` in them fail in formgrader
Discovered when using  `notebook: 6.4.11` and `nbgrader: 0.7.1` under linux

Tested & confirmed using `notebook: 6.4.12` and `nbgrader: 0.8.1` under linux

### Expected behavior

When collecting notebooks known to be submitted, the `# Submissions` column should give a value, and a link to be able to grade submissions

### Actual behavior

When collecting notebooks known to be submitted, the `# Submissions` column remains 0

### Cause of the behavior

There are a number of places that use `regexp` to disassemble a path to find details of course-code, assignment-code, student-code, and/or notebooks.

There is a problem if any of those elements have characters in them that can be interpreted as a "regex special character" [. $ * + ? {} \ [] | () ... and various combinations involving the above.]

For example, if an assignment is called `123 (abc)` - it will happily flow through the system, however formgrader will always count `0` students as NbGrader.api.get_submitted_students() has a regexp `<snip>/submitted/(?P<student_id>.*)/123 (abc)` ... and this matches `123 abc`, with the `abc` in a MatchObject, **not* `123 (abc)`

### Tested solution

Increase the number of characters tested for validation in `assignment_id`

- Edit `server_extensions/formgrader/static/js/manage_assignments.js` in the `var createAssignment` section (used in the formgrader UI)
- Edit `coursedir.py` in `def _validate_assignment_id(..` (needed for the CLI commands)

I suggest the following characters will confuse the regexp system, and should be excluded: `+()/\\[]{}$^`

### PR DESCRIPTION
**Pull request by perllaghu**
This extends the list of banned assignment-name characters beyond `+` to include a bunch that break the path regex code.

closes #1738

### CODE REVIEW

**Comment by brichet** [comment]
Thanks @perllaghu.

I wonder if there could not be a way to manage special characters when running the regex match. Something like `re.escape`, to avoid constraining the assignment name.

**Comment by brichet** [comment]
On my side there is some confusion in this PR, I see some modifications already in the branch `main` (e.g. *zero point validation*).

**Comment by perllaghu** [comment]
> Thanks @perllaghu.
> 
> I wonder if there could not be a way to manage special characters when running the regex match. Something like `re.escape`, to avoid constraining the assignment name.

This is essentially an extension of the existing routine - which prevent `+` in assignment names.

**Comment by perllaghu** [comment]
> On my side there is some confusion in this PR, I see some modifications already in the branch `main` (e.g. _zero point validation_).

I'll rebase on master :)

**Comment by smith-kyle** [comment]
Just a heads up, you can review notebook changes like this using [GitNotebooks](https://gitnotebooks.com).

e.g. this pull request [https://gitnotebooks.com/jupyter/nbgrader/pull/1768](https://gitnotebooks.com/jupyter/nbgrader/pull/1768)

It's free for public repos, so might be helpful for y'all.

**Comment by lahwaacz** [comment]
The last commit https://github.com/jupyter/nbgrader/pull/1768/commits/88915ab776de97b52d754d479709fbc36f84fa7b is very confusing: it includes changes from https://github.com/jupyter/nbgrader/commit/67069391deaf4ac390952e633926631b5271a328 (in `main`), reverts 2 previous commits in this pull request and maybe also some unrelated changes (I can't tell at this point).

Please do an [interactive rebase](https://thoughtbot.com/blog/git-interactive-rebase-squash-amend-rewriting-history), _drop_ the reverted commits, _squash_ corrections into previous commits and overall make sure that this pull request can be properly reviewed.

**Comment by brichet** [comment]
> This is essentially an extension of the existing routine - which prevent `+` in assignment names.

Agree, let's move forward with this PR and open an issue to allow these character in future development.
@perllaghu can you clean this PR please ?

**Comment by perllaghu** [comment]
The sane move now will be to drop this & redo the work on a fresh `master`

**Pull request closed without merging**
