### PR TITLE
Upgrade nbconvert

### PR DESCRIPTION
**Pull request by brichet**
This PR upgrades dependencies to `nbconvert>=6` ,and `jinja2>=3`.

- preprocessing cell is now done with the native `nbclient` method (instead of overriding the `nbconvert<6` one)
- `feedback` and `formgrade` templates are now using the `nbconvert>6` template system
- uses `ClearMetadataPreprocessor` in `exporter` when running tests to remove the new `execution` which which was breaking comparison tests

Closes https://github.com/jupyter/nbgrader/issues/1373, https://github.com/jupyter/nbgrader/issues/1382

### CODE REVIEW

**Comment by BertR** [comment]
Thanks for this PR @brichet

**Comment by brichet** [comment]
@BertR I made some changes to fix nbextensions error, and also to avoid error with date format and language in test browser (my locales are not English, so some tests were failing).

**Comment by BertR** [comment]
Great stuff!

**Comment by brichet** [comment]
Thanks @BertR

**Comment by jhamrick** [comment]
Does this supersede #1421?

**Pull request merged**
