### PR TITLE
Overwrite files with master version when autograding

### LINKED ISSUE #170: Replace master files in nbgrader autograde
If an assignment has supplementary files (like .py files), the students' versions of these should be replaced with the master version during `nbgrader autograde` (this can probably be detected automatically from just looking at the source directory). Additionally, there could be a config option for allowed additional files in the student's submission, and an option to delete any other files that aren't from  the source and aren't allowed.

### PR DESCRIPTION
**Pull request by jhamrick**
This replaces files with their master versions (if they exist in the source directory) when running `nbgrader autograde`. It does this by breaking up the autograding into two steps: first, a "sanitize" step that replaces files, clears outputs, and replaces cells, and second, the actual autograding step where the notebooks are executed and the grades saved into the database.

Fixes #170 

ping @ellisonbg , as I don't want to merge this if it is going to cause any problems for you.

### CODE REVIEW

**Comment by ellisonbg** [comment]
Needs rebasing.

**Comment by ellisonbg** [comment]
A few questions first:

* How does an instructor say which files are to be overcopied or not?
* In what situations have you run into a need for this?

**Comment by jhamrick** [comment]
> In what situations have you run into a need for this?

There's two cases where this might be necessary:

1. You provide students with a supplementary file, but then realize there's a bug in it. You post a clarification to your class saying they should make a change to the file and that they need to pass the tests with this change, for example. However, not all students may make the change, so you want to overwrite the file for everyone during grading to make sure that everyone is actually running the same code.

2. Relatedly, it's possible students could change the code or data that is given to them so that they pass the tests without actually completing the assignment. I've also had students who changed the code they were given to add print statements -- which is fine, except that then during grading you can end up with a cell output that is hundreds or thousands of lines long, so it's nice to be able to revert back to the version of the code that they were given when the assignment was released.

> How does an instructor say which files are to be overcopied or not?

Good question. At the moment, it will overwrite all of the files that have a version in the source directory (with the exception of `.ipynb` files), but perhaps there should be a configurable option to either whitelist or blacklist files for overwriting. My preference would be a blacklist -- by default, overwrite everything, but allow some things to be excluded if you actually are expecting students to change them. What do you think?

**Comment by ellisonbg** [comment]
OK thanks for the clarification. I think we should keep this as simple as possible for now with no whitelist or blacklist and see how it goes. The problem with getting into that is that we have to possibly think about a per assignment config and that is complexity I would rather do without. I haven't had a chance to review the code of this, but I am +1 on the idea of this implementation.

**Comment by jhamrick** [comment]
Yeah, I also don't really want to deal with having per-assignment config (at least not for the moment -- I think we'll probably need it eventually, but I don't have a clear enough idea of how to do that cleanly yet).

So, ok, I'll rebase this and then merge and we'll see how it goes. Definitely let me know if you run into any cases where you *don't* want to have this functionality.

**Pull request merged**
