### PR TITLE
Better UI for create assignment extension

### LINKED ISSUE #153: Proposal: remove solution cells
I think the concept of solution cells is confusing, because you can just make the solution region (e.g. with `### BEGIN SOLUTION`), and so then it's less clear what the difference between solution cells and grade cells is. I propose getting rid of the solution cell checkbox, and just requiring people to use the solution region annotation. Then, in the cell toolbar, we can change the "grade?" checkbox to be different for markdown vs code cells:

* for markdown cells, the label should be something like "written answer?"
* for code cells, the label should be something like "tests for code answer?"

Under the hood, we'll still have the concept of solution cells and grade cells, but I think in the UI the different pieces are just confusing.

For my proposed new cell type (#131), we could add a checkbox that has a label saying "prevent edits?" or something like that. It would automatically get checked on code cells that are grade cells, and would be impossible to check on markdown cells that are grade cells.

@ellisonbg what are your thoughts on this?

### LINKED ISSUE #242: Allow solution+grade cells for free response coding
I often find myself wanting students to freely code and write their own tests in a cell. In the current version I have to create two cells:

1. A solution cell that has my version of the code.
2. A grade cell with `assert True` as a placeholder to grade the students work.

The problem is that I have to create two cells *and* the comments in the formgrader go with the placeholder cell, not the student's code.

If we allow a code cell (like a markdown cell) to be solution+grade, it would be become much nicer to do this type of thing. Also, our current UI allows users to have a solution+grade code cell, so the fact that is doesn't work is some manner of bug.

### PR DESCRIPTION
**Pull request by jhamrick**
This is my first attempt at creating a better UI for creating assignments, based on various discussions in person and in issues #242 and #153. The UI added in this pull request introduces a dropdown box with various options. For markdown cells, there is only one option ("manually graded answer") and for code cells, there are three options ("manually graded answer", "autograded answer", and "autograder tests"). Here's an example "autograded answer" cell:

image

Here's an example "autograder tests" cell:

image

Here's an example "manually graded answer" cell:

image

This should be fully compatible with existing assignments created in nbgrader with the exception that it requires you to also put an id for "autograded answer" cells (whereas previously you would not have to do this). 

I would love to get some feedback on whether this is intuitive and if it covers all use cases, particularly from @ellisonbg @smeylan @ddbourgin @suchow if any of you have opinions!

* Fixes #242 
* Fixes #153

### CODE REVIEW

**Comment by jhamrick** [comment]
Updated the tests so they should pass, and also made the colors be more consistent with the rest of the nbgrader UI (e.g. formgrader and feedback):

image

---

image

---

image

**Comment by ellisonbg** [comment]
I will have a look at this soon - I am just finishing finals this coming
week and will start to have more time. One initial feedback - I do think we
need to make it possible to have a code cell that is both grade+solution
for free form coding. That is one of the most common patterns that I used
this quarter in creating assignments.

On Sat, Jun 6, 2015 at 6:13 PM, Coveralls <notifications@github.com> wrote:

> [image: Coverage Status] <https://coveralls.io/builds/2749983>
>
> Coverage increased (+0.06%) to 95.02% when pulling *3b63fbc
> <https://github.com/jupyter/nbgrader/commit/3b63fbc6d5e8990f6ff75a484ab4892ee877293b>
> on jhamrick:cell-types* into *cac5503
> <https://github.com/jupyter/nbgrader/commit/cac55037e43be04b586fc7936f12352ed95eb2a3>
> on jupyter:master*.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/nbgrader/pull/290#issuecomment-109665941>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by jhamrick** [comment]
Yes, that is definitely possible -- you can choose "manually graded answer"
for both written answers and code answers.

**Comment by jhamrick** [comment]
I will add an example cell like this to the documentation notebooks so examples of every cell type are fully accounted for.

**Comment by jhamrick** [comment]
Updated documentation and tests. Here's a screenshot of a free-response code cell:

image

**Comment by Carreau** [comment]
test restarted should pass, we pinned `jsonschema !=2.5.0`

**Comment by jhamrick** [comment]
Hmm, I suspect it probably needs to be fixed in the 3.x branch of IPython as well as in jupyter/nbformat -- nbgrader relies on 3.x rather than 4.0 currently.

**Comment by Carreau** [comment]
Good point. https://github.com/ipython/ipython/pull/8517

**Comment by ellisonbg** [comment]
I like the three options (Manually graded answer, Autograded answer, and Autograder tests) and think that this will simplify and clarify the assignment creation process. The only question I have is if we want to use the word "solution" rather than "answer" in these descriptions (I am not sure).

Questions:

* Does this preserve the existing metadata usage so that previously created assignments will still work fine?
* Can you still leave out the `### BEGIN/### END` blocks if you select one of the answer types?
* Can the `### BEGIN/### END` blocks be used with both manually and autograded answer types?

**Comment by jhamrick** [comment]
I feel like I prefer "answer" because "solution" can be a bit ambiguous -- does it mean a student's solution, or *the* solution? At least to me, "answer" very strongly implies "student's answer". So by using "answer" in the drop down menu for cell type, we're telling instructors to denote whether this is a cell where students will write their answers, and then additionally instructors can mark what the actual solution is by using the `### BEGIN SOLUTION` and `### END SOLUTION` syntax.

> Does this preserve the existing metadata usage so that previously created assignments will still work fine?

Mostly. There is one major change that will make things not work quite the same, which is that this now requires you to put in ids for *all* cell types rather than just grade cells. So if you want to use the same assignment after these changes take effect, you'd have to go in and make sure all the cells have ids.

This is annoying, but I really think it is a necessary change for all cells to have ids. I can't really fix things like #108 until this is the case.

> Can you still leave out the ### BEGIN/### END blocks if you select one of the answer types? Can the ### BEGIN/### END blocks be used with both manually and autograded answer types?

Yes to both questions, though I should probably add some more explicit test cases for this.

**Comment by jhamrick** [comment]
Ok, I have added some more test cases for the handling of the ### BEGIN/### END blocks. The behavior is (which is pretty much the same as before, with a few small changes):

1. If it is marked as a solution cell (e.g. manually graded answer or autograded answer) and there are ### BEGIN/### END blocks, the blocks will be replaced by the code/text stubs.
2. If it is marked as a solution cell and there are *no* ### BEGIN/### END blocks, the entire cell contents will be replaced by a code/text stub.
3. If it is not marked as a solution cell and there are ### BEGIN/### END blocks, an error will be thrown because any sell with a solution in it must be marked as a solution cell and given an id.

**Comment by jhamrick** [comment]
Based on a conversation Brian and I had:

* Just validate ids on a save event
* Does needs manual grade work with manually graded code cells?

**Comment by jhamrick** [comment]
Ok, just checked this and "needs manual grade" does work with manually graded code cells. I will go ahead and merge this now and then change when the cell id validation occurs in a separate pull request.

**Pull request merged**
