### PR TITLE
Fixes selenium tests

### PR DESCRIPTION
**Pull request by brichet**
EDIT : Fix https://github.com/jupyter/nbgrader/issues/1612

All the methods like `find_element_by_*` and `find_elements_by_*` have been removed from selenium 4.3.0.

This PR replaces them by `find_element(By.*, ...)` and `find_elements(By.*, ...)`.

### CODE REVIEW

**Comment by brichet** [comment]
@meeseeksdev backport to main

**Review by jtpio — APPROVED** [review]
Looks good, thanks!

Looks like this should fix https://github.com/jupyter/nbgrader/issues/1612? If so then probably the pin added in https://github.com/jupyter/nbgrader/pull/1611 can be removed?

**Comment by brichet** [comment]
> Looks like this should fix #1612?

Yes, forgot to mention it.



> If so then probably the pin added in #1611 can be removed?

It was not ported on this branch (`0.7.x`), only on `main`, but I'm backporting these changes on `main` and will remove the pin.

**Comment by jtpio** [comment]
> It was not ported on this branch (`0.7.x`), only on `main`, but I'm backporting these changes on `main` and will remove the pin.

Ah right, sounds good :+1:

**Pull request merged**
