### PR TITLE
Make the hub_base_url configurable.

### PR DESCRIPTION
**Pull request by jdfreder**
@jhamrick 

This is required for complex deployments.

I have an SSL terminating nginx sitting in front of the Hub and nbgrader.  I need to direct clients to nginx's HTTPS domain.

### CODE REVIEW

**Comment by jhamrick** [comment]
Thanks!

**Comment by jonathanmorgan** [comment]
I believe the problem we are having with nbgrader and jupyterhub SSL is related to this same file - looks like "http" is hard-coded in the base URL.  Would be good to be able to configure it to use "https" instead, if needed.

**Comment by jhamrick** [comment]
Aha, yes, that is probably the case. Can you open a new issue for that and I'll submit a fix?

**Comment by jonathanmorgan** [comment]
certainly.  Thanks.

**Pull request merged**
