### PR TITLE
Actually prune if empty dict, not other way around.

### PR DESCRIPTION
**Pull request by Carreau**
Or you would just deactivate all extension, which much likely not what
you want to do :-)

---- 

I think that make sens. (haven't tried though) 

Can comme up with a test also.

### CODE REVIEW

**Comment by Carreau** [comment]
Ok, the first commit should fail, and the second pass.

**Comment by Carreau** [comment]
Travis is happy but coveralls refuse to post the new version :(

**Comment by jhamrick** [comment]
Oof, good catch!

**Comment by Carreau** [comment]
> Oof, good catch!

Yeah, I was doing completely something else totally unrelated and far from my computer when my brain  told me "Hey ! Hey! There is no `not`, you should put one". One of these moment where your wondering how you think of that.

**Comment by jhamrick** [comment]
Hooray for cognitive processes that are still doing stuff in the background even when the rest of our brains are not :smile:

**Pull request merged**
