### PR TITLE
Add and use a Gradebook contextmanager for DbApp and DbApp tests

### LINKED ISSUE #631: Fix nbgrader db tests on windows
Apparently they are broken, sigh:

https://jenkins.jupyter.org/job/nbgrader/_mark=python,_pyversion=3.5,label=windows/96/console

### PR DESCRIPTION
**Pull request by lgpage**
Should fix #631

cc @ellisonbg

### CODE REVIEW

**Comment by lgpage** [comment]
@jhamrick I started messing around with AppVeyor CI for nbgrader and quickly tested this [here](https://ci.appveyor.com/project/lgpage/nbgrader) and the ``python`` tests passed, but if you could please confirm if the tests pass on jenkins or not.

**Comment by jhamrick** [comment]
Nice. This makes me think I really should have just made the `Gradebook` a context manager to begin with, i.e. so you could do `with Gradebook("sqlite:///gradebook.db") as gb:`. But that would be a fairly major change -- maybe something to do for 0.5.0 😉 

I will test this out on Jenkins now.

**Comment by lgpage** [comment]
Yeah making ``Gradebook`` a context manager would be nice :smile:

**Comment by jhamrick** [comment]
Ok, Jenkins finished. The tests are failing on 2.7 but I think that's an unrelated issue. Thanks for fixing this!

**Pull request merged**
