### PR TITLE
Fix Contributor Guide link

### PR DESCRIPTION
**Pull request by vinaykola**
Fixes https://github.com/jupyter/nbgrader/issues/420.

### CODE REVIEW

**Comment by vinaykola** [comment]
@jhamrick I'm not entirely sure why tests are failing. It seems unrelated to my (innocuous) changes.
```
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/coverage/data.py", line 477, in update
    raise CoverageException("Can't combine line data with arc data")
coverage.misc.CoverageException: Can't combine line data with arc data
The command "invoke tests --group="$GROUP"" exited with 1.
```

**Comment by willingc** [comment]
@vinaykola Not related to the tests failing...please use ``https`` for the link https://nbgrader.readthedocs.org/en/latest/contributor_guide/index.html

@jhamrick A couple of things:
1. FYI. RTD is currently displaying Stable build for the default instead of Latest. Not sure which your prefer as default.
2. Once Travis builds cleanly, you may wish to double check that the RTD build (latest) is also passing (see https://github.com/jupyter/notebook/pull/492)

Also, nedbat has a new release of coverage out.

**Comment by vinaykola** [comment]
@willingc Updated to use `https`.

**Comment by jhamrick** [comment]
Thanks @vinaykola ! Just a quick update that I will review this next week -- I'm currently rushing to get a paper submitted before the deadline, so won't have time to look at this right away.

@willingc Yeah, I specifically picked the stable build for the default because that's what most people will be looking for if they have nbgrader installed from pip. There are currently issues with my RTD builds though that I'm aware of and am going to address as soon as I have time, hopefully next week...

**Comment by willingc** [comment]
@jhamrick FYI. This looks good to merge. It's in the Contributing.md file in the root of the repo. I'll be prepping for Grace Hopper workshop and two panels this week. If I get a chance, I'll take a look at the build. Good luck on the paper :sunflower: 

@vinaykola Your change looks good to me. Thanks for the contribution. :penguin:

**Comment by 8leggedunicorn** [comment]
TMI but I'm betting this has much to do with the version of `Coverage` being used.  This appears to be related if not the same upstream bug with issues running `Pytest-cov` and `Coverage` together that was encountered and fixed roughly two months ago,

https://bitbucket.org/ned/coveragepy/issues/399/coverageexception-cant-combine-line-data

where the issue were empty line being generated by pytest-cov,

https://bitbucket.org/ned/coveragepy/commits/74e2f7c366a2

allowing for `Coverage` to interpret these as lines as opposed to arcs.  The errors here are line for line exactly the same as provided in the first link except for small changes to the line number, see lines

https://travis-ci.org/jupyter/nbgrader/jobs/83507415#L458-L459

note I took one of the random failed jobs using Python 2.7 but each of the four failed tests failed in exactly the same manner,
```
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/pytest_cov/plugin.py", line 160, in pytest_sessionfinish
    self.cov_controller.finish()
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/pytest_cov/engine.py", line 131, in finish
    self.cov.combine()
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/coverage/control.py", line 787, in combine
    self.data_files.combine_parallel_data(self.data, aliases=aliases, data_paths=data_paths)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/coverage/data.py", line 700, in combine_parallel_data
    data.update(new_data, aliases=aliases)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/coverage/data.py", line 477, in update
    raise CoverageException("Can't combine line data with arc data")
```

**Comment by willingc** [comment]
@8leggedunicorn I would agree that you are on the correct path re: the errors. Nice documentation of the coverage changes. Do you want to look at the ``travis.yml`` and ``flit.ini`` to  propose a fix?

**Comment by 8leggedunicorn** [comment]
@willingc Sure I'll take a stab at it.

**Comment by jhamrick** [comment]
@8leggedunicorn thanks for tracking that down! It looks like that issue was closed before coverage 4.0 proper was released, and it also looks 4.0 proper is what was installed (https://travis-ci.org/jupyter/nbgrader/jobs/83507415#L284), so it's odd that we're seeing that... but anyway, I will open a separate issue for that and we can keep trying to debug there. Thanks!

@vinaykola this looks great, I am going to go ahead and merge even though the tests will now fail on master, but hopefully we can figure out the issue with coverage and fix that soon. Thanks!

@willingc thanks for reviewing stuff and responding while I was away and super busy the last few weeks, I really appreciate it!

**Comment by willingc** [comment]
@jhamrick No problem. Hope the paper went well. I'll be at Grace Hopper all next week doing a workshop and two panels. Send any cool students my way. There will be an open source booth.

**Pull request merged**
