### PR TITLE
Write documentation on creating releases

### PR DESCRIPTION
**Pull request by jhamrick**
Ping @willingc for docs review

This streamlines the workflow for creating a release by adding a few helper scripts and documents all the necessary steps. This is as much for myself as it is for other contributors as I always forget exactly what needs to be done in creating a release 😜

### CODE REVIEW

**Comment by jhamrick** [comment]
I'm going to go ahead and merge this but happy to make another PR if there are further things to change!

**Comment by willingc** [comment]
@jhamrick Thanks for the ping. I've been swamped. I'll give it a read this weekend. Is that soon enough for 0.3.0?

**Comment by jhamrick** [comment]
Sure, no rush! I still have to finish fixing the windows bugs before 0.3.0 can ship. I am going to try to get to that this weekend but I also have been swamped, so who knows. So no worries if you don't have time soon :-)

**Comment by willingc** [comment]
Cool. I'll grab my Windows laptop when I'm home tomorrow. I do want to read it. You know I :heart: education.

**Comment by jhamrick** [comment]
Ok, awesome, thanks!

You shouldn't need your windows laptop though, I just mentioned windows cause that's the thing *I* still need to do 😜

**Comment by willingc** [comment]
I have been meaning to test some things anyways on Windows re: install of notebook. Have you seen some of the stuff @carolynvs has been working on re: Carina and [How to Whale](https://howtowhale.com/) and [jupyterhub-carina](https://github.com/jupyterhub/jupyterhub-carina/pull/1)? I'm hopeful that there may be a very user friendly nbgrader deploy for a class  that comes out of this work :smile:

P.S. Carolyn gets "quote of the day" for "play chaos monkey":
> This scenario only happens when I "play chaos monkey", deleting the cluster while the server is running and doesn't happen with normal usage.

**Comment by jhamrick** [comment]
I haven't seen it, but it looks awesome! It would be so great if we got a friendly nbgrader deploy out of it :-)

👍 for chaos 🐒

**Comment by willingc** [comment]
@jhamrick I had a chance to review this morning. This is wonderful work. I really like your focus on automating things. :tada:

As an aside, perhaps many of our projects should receive the same automation updates...

**Pull request merged**
