### PR TITLE
Build docs

### LINKED ISSUE #117: Come up with a better solution for building docs
Docs that are in master should be just the manually written content, with nothing generated (i.e., IPython notebooks with *no* output from the cells). We should actually compile the docs and commit the output to a different branch, and maybe we can set up something on Travis to do this automatically every time there is a commit to master. This will help to minimize merge conflicts and also remove the problem of having to remember to regenerate the docs all the time.

### PR DESCRIPTION
**Pull request by jhamrick**
This is an attempt to close #117

Continuation from #124

### CODE REVIEW

**Comment by Carreau** [comment]
OK, this is still technically a PR, so I don't know how it will behave. It seem to show two parallel travis build...

**Comment by jhamrick** [comment]
Yep, this is a PR, but it's also a branch on the jupyter repo (rather than my fork), so it should build the docs on the push build but not the PR build.

**Comment by Carreau** [comment]
> Yep, this is a PR, but it's also a branch on the jupyter repo (rather than my fork), so it should build the docs on the push build but not the PR build.

Nop. It choke on `rm -r *` try to remove the `.git` folder (weird) and no `-f` mean it's waiting for user to pres `y`...

**Comment by Carreau** [comment]
Oh, it's actually choking on `ipython/.git` folder.... I guess we should clone in ~/ not in ~/nbgrader. I'll make a PR.

**Comment by jhamrick** [comment]
Thanks Matthias! Almost there... now apparently it's dying because fabric doesn't do python 3? But all the docs are in python 3 notebooks, sigh. Ok, maybe it is time to switch to invoke, which I'm pretty sure does work on python 3.

**Comment by jhamrick** [comment]
Yesssss it finally works!

**Comment by Carreau** [comment]
:shipit: :ship: :+1:

**Pull request merged**
