### PR TITLE
Fix labextension plutin IDs in the docs

### PR DESCRIPTION
**Pull request by lahwaacz**
See https://github.com/jupyter/nbgrader/discussions/1749#discussioncomment-6709943

### CODE REVIEW

**Comment by brichet** [comment]
Fixes also https://github.com/jupyter/nbgrader/issues/1810

**Comment by brichet** [comment]
Thanks @lahwaacz.

There is also one plugin name not updated in the demos (the other ones have been updated already). Can you fix it in this PR ?
https://github.com/jupyter/nbgrader/blob/f37eede575aa49d27ecbd12871b00f0388279b9c/demos/restart_demo.sh#L80

**Comment by lahwaacz** [comment]
@brichet Done.

**Comment by lahwaacz** [comment]
@brichet Some UI tests failed, but I don't think that's my fault. Can you help?

**Comment by brichet** [comment]
> @brichet Some UI tests failed, but I don't think that's my fault. Can you help?

https://github.com/jupyter/nbgrader/pull/1812 should fix it.
Can you try rebasing ?

**Comment by lahwaacz** [comment]
@brichet Sure, rebased.

**Comment by brichet** [comment]
Thanks @lahwaacz

**Pull request merged**
