### PR TITLE
Move away from using the internal Traitles API to load default configuration.

### PR DESCRIPTION
**Pull request by BertR**
As discovered by @nthiery, the changed internal API in https://github.com/ipython/traitlets
broke the nbgrader build.

This PR implements the change proposed by @minrk, based on the change
to went into ipython here https://github.com/ipython/ipython/pull/10676/files

### CODE REVIEW

**Comment by nthiery** [comment]
I don't know enough the internals to foresee potential side effects, but the code certainly looks nicer after this change!

**Comment by nklever** [comment]
IMHO Issue #1247 will also be solved with this PR

**Comment by jhamrick** [comment]
Awesome, thanks!

**Comment by jhamrick** [comment]
@meeseeksdev backport to 0.6.x

**Pull request merged**
