### PR TITLE
Fix labextension plugin IDs in the docs and demos

### PR DESCRIPTION
**Pull request by lahwaacz**
https://github.com/jupyter/nbgrader/pull/1811 has happened again :facepalm: 

This fixes https://github.com/jupyter/nbgrader/pull/1893

### CODE REVIEW

**Comment by brichet** [comment]
> #1811 has happened again 🤦
> 
> This fixes #1893

Thanks @lahwaacz, my fault again.

Test failures are not related, but let fix them before (I'll do it) and rebase.

**Comment by brichet** [comment]
@lahwaacz can you rebase after https://github.com/jupyter/nbgrader/pull/1928 ?

**Comment by lahwaacz** [comment]
> @lahwaacz can you rebase after #1928 ?

Done

**Review by brichet — APPROVED** [review]
LGTM, thanks @lahwaacz

**Pull request merged**
