### PR TITLE
Update installation.rst

### PR DESCRIPTION
**Pull request by fenwickipedia**
Text formatting change re: https://github.com/jupyter/nbgrader/issues/862

### CODE REVIEW

**Comment by jzf2101** [comment]
@jhamrick i think this is what you were referring to? It looks ok to me

**Comment by fenwickipedia** [comment]
Triggered latest failing build, but only instruction changes in installation.rst.

**Comment by Carreau** [comment]
I restarted the build but the failure seem consistent and unrelated. I think that @jhamrick will be busy for the next week or so, so may not respond. If that's the case I can merge that.

**Comment by jzf2101** [comment]
I'm gonna keep kicking the CI and see if it fixes

**Comment by jzf2101** [comment]
We got this to pass now.  I think it's good to go.

**Comment by fenwickipedia** [comment]
🎆 🍾 🎉

**Comment by jhamrick** [comment]
Thanks @fenwickipedia for the contribution! And thanks @Carreau and @jzf2101 for reviewing and merging in my absence :-)

**Pull request merged**
