### PR TITLE
Update developer installation instructions

### PR DESCRIPTION
**Pull request by cdvv7788**
Make changes as required at https://github.com/jupyter/nbgrader/issues/862

### CODE REVIEW

**Comment by cdvv7788** [comment]
@jhamrick Is this what you had in mind for https://github.com/jupyter/nbgrader/issues/862 ?

**Comment by jhamrick** [comment]
Thanks!

I think it would be a bit clearer for new developers that all three commands should be run if the they are one right after another with no linebreaks/comments, e.g.:

```
jupyter nbextension install --symlink --sys-prefix --py nbgrader
jupyter nbextension enable --sys-prefix --py nbgrader
jupyter serverextension enable --sys-prefix --py nbgrader
```

The other documentation (e.g. about what the symlink is doing) could go before or after (but ideally not as comments in the code block itself).

**Comment by cdvv7788** [comment]
@jhamrick Better?

**Comment by jhamrick** [comment]
Looks great now, thanks!

**Pull request merged**
