### PR TITLE
Create nbgrader quickstart command

### LINKED ISSUE #338: Add example "boilerplate" notebooks for use by instructors
It may be helpful to add notebooks for instructors to use as a baseline example for setting up and grading assignments. For example, take the examples that are spread out across the user guide and make them into "boilerplate" notebooks without all the additional documentation for instructors. The benefit would be that the instructor would have a quick start to setting up a demo.

### PR DESCRIPTION
**Pull request by jhamrick**
Fixes #338 

Ping @willingc -- can you test out this PR and let me know if you think this "quickstart" example works ok?

### CODE REVIEW

**Comment by willingc** [comment]
@jhamrick I had some difficulty testing it this weekend. I wasn't able to get quickstart running which is likely an environment issue on my side. I'll give it a shot later this week and/or we can jam through stuff at the dev meeting.

**Comment by jhamrick** [comment]
Hmm, ok. What error did you get when you tried to run it?

**Comment by willingc** [comment]
Basically quickstart didn't run so I'm almost 99% positive it's pilot error.

**Comment by jhamrick** [comment]
@willingc I have updated the docs for quickstart as per your comments to clarify the course id and the `--force` flag

**Comment by willingc** [comment]
@jhamrick Works as advertised :D 

A nice enhancement might be to output a message after executing quickstart to tell the user how to begin using the quickstart.

**Comment by jhamrick** [comment]
Good idea. I'll add something along the lines of "edit the source files in ... and then release them with `nbgrader assign ps1`" and then also a link to the main docs for further information.

**Comment by willingc** [comment]
@jhamrick Do you want me to merge this as is? Or wait for the enhancement?

**Comment by jhamrick** [comment]
I will make the enhancement first.

**Comment by jhamrick** [comment]
This now will print:

```
$ nbgrader quickstart course101
[QuickStartApp | INFO] Creating directory '/Users/jhamrick/project/misc/course101'...
[QuickStartApp | INFO] Copying example from the user guide...
[QuickStartApp | INFO] Generating example config file...
[QuickStartApp | INFO] Done! The course files are located in '/Users/jhamrick/project/misc/course101'.

    To get started, you can edit the source notebooks located in:

        /Users/jhamrick/project/misc/course101/source/ps1

    Once you have edited them to your satisfaction, you can create
    the student version by running `nbgrader assign ps1` from the
    '/Users/jhamrick/project/misc/course101' directory.

    For further details, please see the full nbgrader documentation at:

        http://nbgrader.readthedocs.org/
```

Does that look good to you @willingc ?

**Comment by willingc** [comment]
@jhamrick This looks great! I am pressing merge :tada:

**Comment by jhamrick** [comment]
Thanks! :smile:

**Pull request merged**
