### PR TITLE
Set CSP frame-ancestors 'self' for nbgrader handlers

### PR DESCRIPTION
**Pull request by jeflem**
This PR solves issue #1870 (formgrader does not show in JupyerLab tab due to JupyterHub >=4.1.0 security settings in HTTP headers).

Starting with JupyterHub 4.1.0 HTTP header
```
Content-Security-Policy:  frame-ancestors 'none'
```
is the default setting instead of
```
Content-Security-Policy: frame-ancestors 'self'
```
See [Mitigating same-origin deployments](https://jupyterhub.readthedocs.io/en/stable/explanation/websecurity.html#mitigating-same-origin-deployments) for some background on this decision and [CSP: frame-ancestors](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors#self) for details on the header.

The `none` header prevents loading of formgrader in a tab of JupyterLab.

The JupyterHub `none` setting overwrites the `self` setting of Jupyter Server running without JupyterHub. See
* [jupyter_server/base/handlers.py#L101](https://github.com/jupyter-server/jupyter_server/blob/74655ce66f36ed85a83591e6658e70ba91232580/jupyter_server/base/handlers.py#L101) for default setting `self` in Jupyter Server,
* [jupyterhub/singleuser/extension.py#L658](https://github.com/jupyterhub/jupyterhub/blob/99b32dd372ae41c14473e543be4c302b80f613aa/jupyterhub/singleuser/extension.py#L658) for default setting `none` in JupyterHub's Jupyter Server extension,
* [jupyterhub/singleuser/mixins.py#L688](https://github.com/jupyterhub/jupyterhub/blob/99b32dd372ae41c14473e543be4c302b80f613aa/jupyterhub/singleuser/mixins.py#L688) for default setting `none` in JupyterHub's code for classic notebook.

To allow embedding of nbgrader's formgrader (and possibly other nbgrader components) without affecting security of other JupyterHub components this PR sets `frame-ancestors` to `self` for responses of nbgrader handlers only.

The class `BaseHandler` modified by this PR is a subclass of [`tornado.web.RequestHandler`](https://www.tornadoweb.org/en/stable/web.html#tornado.web.RequestHandler), which provides the [`set_header`](https://www.tornadoweb.org/en/stable/web.html#tornado.web.RequestHandler.set_header) method.

### CODE REVIEW

**Comment by brichet** [comment]
@jeflem I took the liberty to merge main is this PR to try to fix the `check_release` test, as mentioned at https://github.com/jupyter-server/jupyter_releaser/issues/593#issuecomment-2478628377

**Comment by LukasMueller187** [comment]
Hi,
just wanted to check in here because we do have problems with clients using iPads (browser doesn't matter). Feedback html files are rejected because of the frame-ancestors directive.
I thought 0.9.4 would fix it but it doesn't.
Manually setting the header to 'self' again in (our case) apache does solve the issue, but as stated in the first post this is discouraged.

Any ideas?

**Comment by brichet** [comment]
Is this only failing on IPads ?

> Manually setting the header to 'self' again in (our case) apache does solve the issue, but as stated in the first post this is discouraged.

What do you mean by manually ? in the config ?
What is the "first post" you are mentioning ?

**Comment by LukasMueller187** [comment]
Yes it seems to only fail on iPads (and maybe iPhones), so I'm guessing it's an iOS issue.
I narrowed it down to being an issue with html files, as they are always served as a blob. As stated in the error message, iOS seems to reject this blob. In my understanding, it shouldn't (like all desktop browsers do).

By manually I mean configuring apache to set headers to 'self' for frame-ancestors and by first post I mean the first post in this issue.

However, this doesn't seem to be an issue with nbgrader. But I don't know where to file the bug (Lab or Hub or webkit iOS itself).

**Comment by brichet** [comment]
Thanks for the clarification

**Pull request merged**
