### PR TITLE
Fix nbextension tests

### LINKED ISSUE #694: Investigate why nbextension tests keep failing
The nbextension tests seem to have a much higher rate of spurious failures recently. They aren't real failures, as restarting the tests seems to fix it, but it is highly annoying.

### PR DESCRIPTION
**Pull request by lgpage**
This sets the course element (`course_list_default`) text before loading assignments and splits the test wait into two part:
- wait for courses to be loaded, then
- wait for assignments to be loaded

Should fix #694 properly.

### CODE REVIEW

**Comment by willingc** [comment]
@lgpage I'll let @jhamrick review this as she is better than me with frontend stuff. If we haven't said it enough recently, thank you so much for all of the contributions that you have made to nbgrader. :cake:

**Comment by lgpage** [comment]
:smile:

**Comment by jhamrick** [comment]
Thanks for figuring this out!

I guess it was the ability to switch courses that introduced this issue? It's weird that it really didn't seem to be a problem until recently. Maybe Travis has slowed down further or something since then.

**Comment by jhamrick** [comment]
And yes, 👍  to what @willingc said 😄

**Comment by lgpage** [comment]
I think is was the combination of the switch courses and the additional test for missing / renamed notebooks. It takes about 5-6s on my machine for the course dropdown to be clickable.

**Comment by willingc** [comment]
Happy to merge. Thanks @jhamrick for the review.

**Comment by jhamrick** [comment]
Ah, got it.

Yes, it is also slow for me. The reason is because it actually has to shell out to the command line apps rather than running them in the same python session, and the reason it can't run them in the same python session is because the `NotebookApp` and `NbGrader` both inherit from `JupyterApp` which is a singleton, so it raises an error if you try to instantiate `NbGrader` within the `NotebookApp`. Fixing this would require a fair bit of refactoring, but maybe it's worthwhile to open an issue about it...

**Comment by jhamrick** [comment]
See #705

**Comment by jhamrick** [comment]
@meeseeksdev backport to 0.4.x

**Pull request merged**
